[package]
name = "rptime"
version = "0.0.1"
authors = ["MierBen <mrben838@gmail.com>"]
description = "Task-based CTF competition system."
edition = "2018"


[dependencies]
actix = "0.8.3"
actix-cors = "0.1.0"
actix-web = { version = "1.0.7", features = ["rust-tls"] }
actix-web-actors = "1.0.2"
actix-files = "0.1.4"
diesel = { version = "1.4.2", features = ["postgres", "r2d2"] }
env_logger = "0.6.2"
log = "0.4.8"
serde = { version = "1.0.101", features = ["derive"] }
uuid = { version = "0.7.4", features = ["v4"] }